dubbo:
  application:
    name: dubbo_provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
    host: 127.0.0.1
  scan:
    base-packages: org.lanqiao
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://49.234.77.189:3306/bilibili?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai

    # solr配置
 # data:
  #  solr:
   #   zk-host: http://localhost:8983/solr
