dubbo:
  application:
    name: dubbo_provider
  registry:
    address: zookeeper://49.232.26.166:2181
#    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882
    host: 127.0.0.1
  scan:
    base-packages: org.lanqiao
spring:
  datasource:
    username: root
    password: bili3.14159
    url: jdbc:mysql://49.234.77.189:3306/bilibili?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    username: sonnie_yyds@qq.com
    password: meifunitfnkmbfgh
  redis:
    host: 49.232.26.166
    port: 6379
    password: sonnie
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    database: 0
server:
  port: 8081